### ISSUE TITLE
Issues with the "Edit SQL files" and related docs for a non-software dev audience

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/kingfisher-summarize#135]
I went through the "Edit SQL files" docs with 2 of our analysts, here are some issues we ran in to. A lot of these are not things that are "wrong" per se, but problems we ran into because people who aren't software devs don't necessarily have all the implicit knowledge.

ReadTheDocs: https://kingfisher-views.readthedocs.io/en/latest/develop/sql.html
GitHub: https://github.com/open-contracting/kingfisher-views/blob/master/docs/develop/sql.rst

* [x] If you're coming to this page new to running Kingfisher locally, then you have to navigate through several pages to find all the vagrant steps.
https://kingfisher-views.readthedocs.io/en/latest/develop/sql.html → https://kingfisher-views.readthedocs.io/en/latest/develop/setup.html → https://kingfisher-vagrant.readthedocs.io/en/latest/
(And then you have to realise when to return to the parent page.)

https://kingfisher-vagrant.readthedocs.io/en/latest/#starting-and-building-the-vagrant-box
* [x] It could be clearer where to run the `vagrant up` command, particularly as people returning to work they did earlier will have done all the git clone steps.

https://kingfisher-views.readthedocs.io/en/latest/develop/setup.html#load-data
* [x] It was not immediately obvious that the collection name did not need to actually be surrounded by curly braces.

* [x] Step 2 of https://kingfisher-views.readthedocs.io/en/latest/develop/setup.html#load-data sometimes has an error:
```
psycopg2.errors.UndefinedTable: relation "views.read_only_user" does not exist LINE 1: SELECT username FROM views.read_only_user
```
I think this is expected (I've seen the same error, and wherever I was in the docs told me to expect it), but the docs here don't tell you this.

https://kingfisher-views.readthedocs.io/en/latest/develop/setup.html#load-data
"Look at the data that has been created"
* [ ] Would be useful to have a pointer here on how to do this. I know there's a note in the Prerequisites section above, but people missed this.
* [ ] Also useful would be an example command to check a table exists.

https://kingfisher-views.readthedocs.io/en/latest/develop/sql.html#review-changes
* [x] People missed the "either" here, so emphasising that, or putting an "AND/OR" between the bullets could be useful.

**Comment by mrshll1001** [comment]
Looks good!

**Comment by jpmckinney** [comment]
> I think this is expected (I've seen the same error, and wherever I was in the docs told me to expect it), but the docs here don't tell you this.

It's not expected. I fixed Vagrant's installation of Views.

**Comment by jpmckinney** [comment]
> If you're coming to this page new to running Kingfisher locally, then you have to navigate through several pages to find all the vagrant steps.

I really don't think we want to duplicate instructions (which always, always end up going out of sync eventually, which confuses users even more). I think a challenge with `setup.rst` was that it mixed setup instructions, how-to guides, and explainers – so it was hard to know how much of the page was actually relevant to setup. I've moved these to new pages now. Kingfisher Vagrant's docs should also be split into shorter pages (at least one setup page and another how-to page).

**Comment by jpmckinney** [comment]
Created https://github.com/open-contracting/kingfisher-vagrant/issues/356 for another bullet above about Vagrant.

**Comment by jpmckinney** [comment]
Noting that Kingfisher Vagrant has fallen behind Kingfisher Summarize, and it will again fall behind Kingfisher Process as we move to the Django branch. OCP has no interest in maintaining Kingfisher Vagrant, as it's fairly simple to just install each component on the main system – and this only needs to be done once.

**Comment by jpmckinney** [comment]
I completed most tasks, and the remainder were prioritized by the helpdesk as low priority, because in the end, analysts have not made any changes themselves to Kingfisher Summarize. The docs are still useful for new developers, though.
