### ISSUE TITLE
Ensuring consistency across similar tables

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-summarize#139]
~~`contracts_summary` has milestones columns but `awards_summary` doesn't.~~ (Nevermind: Awards don't have milestones.)

As far as I can tell, the following are consistent (with the addition of an `award_index` or `contract_index` column):

* `*_items_summary`
* `*_documents_summary`
* `*_milestones_summary`
* The party tables (with different column name prefixes): `buyer_summary`, `procuringEntity_summary`, `tenderers_summary` (adds `tenderer_index`) and `award_suppliers_summary` (adds `award_index`, `supplier_index`)

The code presently relies on copy-pasting and careful syncing. We should either write SQL functions to re-use code, or at least add developer documentation or in-line comments to ensure these stay in sync.

**Comment by jpmckinney** [comment]
Related: #203

**Comment by duncandewhurst** [comment]
Closing since https://github.com/open-contracting/kingfisher-summarize/pull/208 is merged.
