### ISSUE TITLE
release_summary: combine release_check and record_check into one column

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-summarize#179]
Unless I misunderstood, only one of these columns will ever be populated since a release can only come from either the `release` or `record` tables in Kingfisher Process.

If we combine them into one `check` column then it will be easier to write queries for structural errors and additional fields as we'll be able to get results for both releases and records in the same column.

cc @yolile @pindec @mrshll1001

**Comment by jpmckinney** [comment]
@yolile I could close this issue, but since we already have all the queries in notebooks already, I think at this point it would be more work to change it – compared to any time it might save. So, I'll close, but can re-open.
