### ISSUE TITLE
PostgreSQL 12: SQL/JSON Path Language

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-summarize#189]
@kindly mentioned that PostgreSQL 12 introduced support for [SQL/JSON Path Language](https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-SQLJSON-PATH) ([tutorial](https://github.com/obartunov/sqljsondoc/blob/master/jsonpath.md)), which could be useful to simplify the SQL queries used in Kingfisher Summarize.

Logging as something to consider in the event we make significant changes to the queries in the future.

**Comment by jpmckinney** [comment]
The server runs on PostgreSQL 11, so we'd have to upgrade PostgreSQL first: https://github.com/open-contracting/deploy/issues/177

**Comment by jpmckinney** [comment]
Pending: https://github.com/open-contracting/deploy/issues/381

**Comment by jpmckinney** [comment]
I've read the tutorial now and skimmed all our queries, and I don't think we have any that both are complex and could be simpler via SQL/JSON Path Language. Most of our complexity is from aggregations, e.g. counts of each document type, or from checking that the JSON types are correct (e.g. for additionalIdentifiers_ids and additionalclassification).
