### ISSUE TITLE
Feature request: Filter collection

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-summarize#190]
For example, we collected all data from the OpenOpps API, and now @camilamila wants to generate summaries for each country within the data.

I think the condition would only need to be added to `release_tmp.sql`

We can maybe add a CLI option (`multiple=True`) to express the field and value to filter on, for example, `--filter buyer.address.countryName="United States"`, and the script would convert this to `data->'buyer'->'address'->>'countryName' = 'United States'`. (Using `>` on the command line would likely lead to user errors if the user forgets to quote the argument, so I used periods which we use elsewhere.)

The script would have to trim quotation marks from the value in this case. Alternately, we can use a pair of options `--filter-field` and `--filter-value` (like [Flatten Tool](https://flatten-tool.readthedocs.io/en/latest/flatten/#filter)), to avoid that step. However, we want to support multiple filters, so in this case, users will have to be careful to use the same order in `--filter-field` and `--filter-value`.

**Update:** Actually, Click has [multi-value options](https://click.palletsprojects.com/en/7.x/options/#multi-value-options) so we can do: `--filter buyer.address.countryName 'United States'`.

**Comment by duncandewhurst** [comment]
It would also be useful to filter by release date. For example, I would like to compare the `field_counts` table for `uk_fts` and `uk_contracts_finder`, but only for 2021, when the publications were running in parallel.

**Comment by yolile** [comment]
> @Camilamila @yolile Based on your work, what common filters do you use?

Release dates, buyer names/ids, and sometimes items classifications

**Comment by Bjwebb** [comment]
I've been trying out some [SQL/JSON Path Language](https://github.com/open-contracting/kingfisher-summarize/issues/189) locally, and it's pretty powerful. It seems to fit this kind of use case well.

Filtering on item classification id: (it defaults to lax mode, where there's no need to explicitly expand arrays)

```sql
AND jsonb_path_match(data.data, '$.contracts.items.classification.id == "SOME-ID"')
```

It looks like it can even handle lookups against the parties array. Here's filtering for a particular buyer name:
```sql
AND jsonb_path_match(data.data, 'exists($.parties[*] ? (@.id == $.buyer.id && @.name == "Buyer Name"))')
```

To support these more complex queries, I think it makes sense to let users pass SQL/JSON Path Language from the command line.
We could also make users supply SQL/JSON Path Language for the simpler cases too, as there's no problem with escaping greater than signs, but it is necessary to get the quotes right.

**Comment by Bjwebb** [comment]
@jpmckinney What do you think?

**Comment by jpmckinney** [comment]
Sounds good. I'll ask Dogsbody about a schedule for upgrading PostgreSQL. It might be early next year, but we'll see.

**Comment by Bjwebb** [comment]
Should I finish off [the PR that works with the current PostgreSQL version](https://github.com/open-contracting/kingfisher-summarize/pull/215), or should I switch to assuming SQL/JSON Path Language support? I'd rather do the latter, but obviously that will delay anything going live.

BTW, there's some useful features in PostgreSQL 13 for dealing with dates within JSON, which are missing in 12. (And probably best to upgrade to the latest version anyway.)

**Comment by duncandewhurst** [comment]
> We could also make users supply SQL/JSON Path Language for the simpler cases too, as there's no problem with escaping greater than signs, but it is necessary to get the quotes right.

I'm happy with this, as long as we can have a documentation page with examples.

> Should I finish off the PR that works with the current PostgreSQL version, or should I switch to assuming SQL/JSON Path Language support? I'd rather do the latter, but obviously that will delay anything going live.

Switching to SQL/JSON Path Language sounds good to me - no issue with delaying the deploy until the server has been upgraded from my perspective.

@jpmckinney just double checking you agree with the above. Thanks!

**Comment by jpmckinney** [comment]
I think the PR is just about ready, so we might as well merge it, and then come back and add SQL/JSON Path support.

**Comment by Bjwebb** [comment]
The PR for the current postgres version is merged and deployed.

I've just made a PR for SQL/JSON Path Language based filters https://github.com/open-contracting/kingfisher-summarize/pull/217 (this can't be merged until postgres is upgraded on the live server).

**Comment by jpmckinney** [comment]
Closing as merged and deployed.
