### ISSUE TITLE
agg_parties: Ignore invalid roles

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-summarize#193]
Some publishers have `roles` as an object instead of an array. Ideally, we can just ignore bad data.

I did a naive attempt in https://github.com/open-contracting/kingfisher-summarize/pull/192 but I'm assuming you can't have a case statement inside a join statement.

**Comment by duncandewhurst** [comment]
What is the current behaviour and what problems does it cause?

**Comment by jpmckinney** [comment]
I think an error is raised. We can create a test case and see what happens.
