### ISSUE TITLE
Add a metadata table with which collections are in which schemas

### ISSUE THREAD

**Issue by pindec** [open-contracting/kingfisher-summarize#197]
Would be helpful to have a metadata views table in Kingfisher, auto populated by views creation, to map collection ids to view names.

Also helpful for this table to store who created it (name of analyst), when, expiration date if known and any other notes (instead of looking in each view for notes).

Use case 1: for any given collection, we can query what views have been generated on it ordered by creation date desc

Use case 2: set up a cron job to delete the views as expiration dates pass. 

Use case 3: cross-collection queries - for each view, if we haven't already run a query on the collection ids it covers, and the expiration date hasn't passed, run a query on it.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/kingfisher-summarize/pull/209
