### ISSUE TITLE
New table request: release related processes

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-summarize#212]
Especially relevant when analyzing FAs related processes, this information is currently only in the JSON column in the `release_summary` table.

**Comment by duncandewhurst** [comment]
Also relevant for analyzing related planning processes (currently used by at least Indonesia Corruption Watch, and likely to become more prevalent under OCDS 1.2)

**Comment by Bjwebb** [comment]
This is now deployed to the kingfisher-process server.
