### ISSUE TITLE
Add a 'fields_list' view

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-summarize#29]
A common need is check how many contracting processes a given set of fields is present in.

This enables us to check what types of use / indicator calculation etc. are possible with a dataset.

@kindly wrote a series of queries which generated a list of field paths present for each ocid, e.g.

| ocid | fields |
| -- | -- |
| ocds-123456-001 | [ocid,id,date,language,tender/id,tender/procurementMethod...] |
| ocds-123456-002 | [ocid,id,date,language,awards/id,awards/value...] |

This issue is to add those queries to kingfisher-views so this information is available for all (compiled) collections.

**Comment by duncandewhurst** [comment]
See https://github.com/open-contracting/kingfisher-process/issues/54 for background.

I understand this will also be implemented in the Data Quality Tools, but it will be useful to have the raw data accessible in kingfisher-views for analysts to queries ad-hoc

**Comment by jpmckinney** [comment]
The DQT will also have the results stored in a PostgreSQL database for analysts to query ad-hoc… Do we really need it twice?

**Comment by duncandewhurst** [comment]
OK, that's good we'll have access to the database.

Will we need to connect with a different set of credentials as to the main kingfisher-process database?

If so we'll need to consider how to handle that in our notebooks and kingfisher-colab

**Comment by kindly** [comment]
The query to do this is easy as there is a flatten function in views.  However, the only reason this is not on views is it was going to take up a lot of disk space.

**Comment by jpmckinney** [comment]
If it's easy, I don't mind putting it in Views. However, my concern around Views is (1) the time it takes to generate views (especially as the size of the database grows and as the number of views grows) and (2) the space the views take.

We can of course increase the size of the server (up to the point of it becoming non-economic), but when we start hitting scaling issues (RAM, disk space), I think it's better to focus those efforts on one approach, since I don't think we have the resources to scale two, similar systems instead of one.

To date, Views makes sense for aggregations (SUM, COUNT, etc.), but for transformations where there's little space efficiency gain (flattening JSON), it might not be the best long-term approach.

**Comment by jpmckinney** [comment]
It's presently on a different physical server, with a separate PostgreSQL database. I'm not familiar with different interconnect options; if not too much trouble, the simplest option is to just have a second SQL connection.

**Comment by duncandewhurst** [comment]
Just a thought on disk space - given that many of the combinations of fields will likely be common (i.e. a single collection might only have have a handful of possible combinations of fields) could we store a unique list of those in one table, and then have a link table which associates them with the ocids?

Like we do with the `data` and `release` tables in kingfisher process.

As mentioned we'll need to make some changes to kingfisher-colab to connect one notebook to two different databases.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kingfisher-views: Add new aggregates/fields](https://trello.com/c/1Ta2HPcR/105-kingfisher-views-add-new-aggregates-fields)

**Comment by jpmckinney** [comment]
Noting that, to my knowledge, this is not solved by Pelican (which is about calculating metrics, without storing the results of each calculation, which would take a huge amount of disk space).

**Comment by kindly** [comment]
Not so concerned about the space for this now due to only doing a few collections at a time.

Could be a separate optional command line option.

**Comment by duncandewhurst** [comment]
This would be useful to calculate the coverage for each indicator in the [usability checks notebook](https://colab.research.google.com/drive/15ofM1htlq02_N0D9Rvas-QpmAUa6JqaO?pli=1) developed by @camilamila

**Comment by duncandewhurst** [comment]
I dug out the old query and added it to the [data import notebook](https://colab.research.google.com/drive/13Q-T5lDRo7e-pm4s5SAPrttBCYHOxTxE#scrollTo=rmTiK5xft12d) for the OC4IDS database.

Here it is for reference. To add it to views we'll need to replace `project_id` with `ocid` and replace `projects` with `data` joined to either `release`, `compiled_release` or `record`. The `where` clause will also need updating to pick up the right `collection_id`. 

```SQL
WITH RECURSIVE paths(project_id, path, "value") AS (
    select project_id,
        (key_value).key "path", 
        (key_value).value "value", 
        'true'::boolean "use_path" from 
    (select project_id, jsonb_each(data) key_value from projects where collection_id = (SELECT id FROM collection ORDER BY id DESC LIMIT 1)) a
  UNION ALL
    (select project_id,
            case when key_value is not null then
                path || '/'::text || (key_value).key::text
            else
                path
            end "path",
            case when key_value is not null then
                (key_value).value
            else
                array_value
            end "value",
            key_value is not null "use_path"
      from
        (select 
            project_id,
            path,
            jsonb_each(case when jsonb_typeof(value) = 'object' then value else '{}'::jsonb end) key_value,
            jsonb_array_elements(case when jsonb_typeof(value) = 'array' and jsonb_typeof(value -> 0) = 'object' then value else '[]'::jsonb end) "array_value"
            from paths
        ) a
    )
)
INSERT INTO
  project_fields
SELECT
  (SELECT id FROM collection ORDER BY id DESC LIMIT 1) as collection_id,
  project_id,
  array_agg(path) as paths
FROM
  paths
WHERE
  use_path
GROUP BY
  project_id;
```

**Comment by duncandewhurst** [comment]
Noting that for calculating the coverage of indicators that relate to objects in arrays, a list of the fields present in each contracting process has some limitations.

**Example 1**

*Indicator:* Proportion of contract awards with less than one week between the award date and start of the contract

*Required fields:* `awards/date`, `awards/contractPeriod/startDate`

In this case, we need to know how many *award objects* have both the required fields, not just how many contracting processes both fields are present in. 

**Example 2**

*Indicator:* Proportion of contracts with an end date greater than the end date in the contract award

*Required fields:* `contracts/period/endDate`, `awards/contractPeriod/endDate`, `contracts/awardID`, `awards/id`

In this case, we need to know how many *award-contract pairs* have all the required fields, not just how many contracting processes both fields are present in.

One solution to this could be to add a `fields_list` column to each table in kingfisher-views, so the `release_summary` table would have a list of all the fields in the release and the `awards_summary` table would have a list of all the fields on each award etc. We would then be able to search for coverage within an object and also to have access to the necessary identifiers to join awards to contracts, e.g. for the latter example:

```sql

SELECT
    (ARRAY['contracts/period/endDate', 'contracts/awardId'] <@ contracts_summary.fields_list
        AND ARRAY['awards/contractPeriod/endDate', 'awards/id'] <@ awards_summary.fields_list) AS measurable,
    count(*)
FROM
    contracts_summary
    LEFT JOIN awards_summary ON contracts_summary.id = awards_summary.id
        AND contracts_summary.award_id = awards_summary.award_id
GROUP BY
    measurable;
```
This does make it a bit harder to automate coverage checks across a range of indicators, but I think we could author a script to generate a query with the correct joins, based on the required fields for the indicator.

**Comment by jpmckinney** [comment]
My assumption is that this would be very slow to run, and might take up significant space, so we should test on some moderately sized collections.

**Comment by duncandewhurst** [comment]
See https://github.com/open-contracting/kingfisher-views/issues/155 for a list of large collections which might be useful for testing

**Comment by jpmckinney** [comment]
The new flatten.sql uses a faster pattern https://github.com/open-contracting/kingfisher-views/issues/159#issuecomment-721358253 The SQL snippet can be modified to follow its template.

**Comment by kindly** [comment]
@jpmckinney better than that.  The SQL just needs to call the (now improved) flatten function.
The point of the flatten function was to be able to the produce the above and coverage easily.

**Comment by Bjwebb** [comment]
I've downloaded all the `columbia_bulk` data locally, to test how long different queries take.

Running summarize as it currently stands took ~14 hours, to create ~5,000,000 rows. I wrote two queries to create fields lists tables for releases (with just 2 columns: id and fields_list), with duplicates, and without. With duplicates took ~35 minutes, whereas without duplicates took ~2 hours. [[Raw timings](https://gist.github.com/Bjwebb/91f4e3d1290ffdea49c6f64bc894608d)]

Both fields lists tables take up a similar amount of space on disk ~5.5 GB, compared to ~20GB for the rest of the summarize tables.

Given the above, I'd suggest the query with duplicates, as I understand the queries we want to write are about whether certain paths exist, which duplicates won't affect.

The above is all for the releases table, adding this to every table would increase the numbers significantly.

**Comment by Bjwebb** [comment]
One option would be to create fields list views for each table. This should reduce disk usage, and move the computation to query time. These views would need to be joined with the relevant query/view for most sql queries we'd want.

**Comment by duncandewhurst** [comment]
@Bjwebb and I discussed this on a call:

* I'm happy with the fields lists containing duplicates as my only use case right now is to check for the presence of fields.
* I would prefer to have a slower generation time for the fields lists and a faster query time. Generating the fields lists can be optional and off by default. This is because we only perform coverage/usability analysis on some datasets but when we do we need to check coverage for lots of indicators (see [indicators linked to OCDS](https://docs.google.com/spreadsheets/d/1j-Y0ktZiOyhZzi-2GSabBCnzx6fF5lv8h1KYwi_Q9GM/edit#gid=612001000) and [red flags to OCDS mapping](https://docs.google.com/spreadsheets/d/12PFkUlQH09jQvcnORjcbh9-8d-NnIuk4mAQwdGiXeSM/edit#gid=0)).

Ben will discuss with @kindly to see if there is a way to have a command-line option to add the fields lists columns to the existing tables, otherwise we might need to generate a separate set of tables and use more joins in analyst queries.

@jpmckinney what level of sign-off or involvement do you want on this issue?

**Comment by jpmckinney** [comment]
Okay, so the two queries are:

```sql
CREATE TABLE flattened_unique AS
SELECT id, array_agg(path)
FROM (
    SELECT id, path
    FROM (
        SELECT *
        FROM release_summary
    ) AS tmptmptmp
    CROSS JOIN flatten(release)
    GROUP BY id, path
    ORDER BY id
) AS tmptmp
GROUP BY id
```

```sql
CREATE TABLE flattened AS
SELECT id, array_agg(path)
FROM release_summary
CROSS JOIN flatten(release_summary.release)
GROUP BY id
```

The unique query can be simplified. I don't see the need for the extra subquery, or for the sort (ORDER):

```sql
CREATE TABLE flattened_unique AS
SELECT id, array_agg(path)
FROM (
    SELECT id, path
    FROM release_summary
    CROSS JOIN flatten(release)
    GROUP BY id, path
) AS t
GROUP BY id
```

Using `EXPLAIN ANALYZE` the only difference is from removing the sort; PostgreSQL is smart enough to handle the subquery without penalty, but we might as well make the SQL easy to read.

Depending on the `work_mem` parameter, a sort might use the disk, which will be very slow. It'd be interesting to know the time without the sort. On our server, `work_mem` is set fairly conservatively to 80MB (default is 4MB).

----

`flatten` builds a table with one row per occurrence of each path in the release; a path will occur once for each entry in an array, hence the duplicates. I think those duplicates are required for the recursion, so we can't eliminate them in the function.

Our options then are how to eliminate them in subsequent queries. The option tested removes them after a cross join. I considered whether a CTE could be used to eliminate duplicates in flatten's output before the join, but not sure it's possible.

----

So, it sounds fine to operate on the release_summary table/view and keep duplicates.

We might as well create an additional `fields_list` table, since `release_summary` is already the joining of many tables; in terms of adding a `fields_list` column to `release_summary`, that's just one more table to join.

If applied to existing tables, this might be an `enrich` command that drops release_summary then re-creates a new one.

I think the cleanest option would be to move the creation of `release_summary` into its own file, and then add a mechanism for inserting the required column/join. This could be using Jinja, or doing a more finicky search-and-replace.

As for sign-off, I'd like to review the PR, since I've spent a fair bit of time cleaning up and adding tests to this repo, and I'd like to keep the quality assurance at the same level.

**Comment by duncandewhurst** [comment]
Thanks, @jpmckinney. I'll leave @Bjwebb and @kindly to agree on the best approach with you, bearing in mind the desired output is a `fields_list` column in each table/view generated by summarize (i.e. not just for `release_summary`).

I mostly came here to note that, once done, we should look at how we can auto-generate queries with the correct joins to check coverage for a collection of fields, after which we can ask Camila to update the usability checks notebook she shared in CRM issue 5084.

**Comment by jpmckinney** [comment]
> I mostly came here to note that, once done, we should look at how we can auto-generate queries with the correct joins to check coverage for a collection of fields, after which we can ask Camila to update the usability checks notebook she shared in CRM issue 5084.

That seems like a job for Kingfisher Colin. Can you create an issue there?

**Comment by kindly** [comment]
@Bjwebb, @duncandewhurst  and I have discussed possible approaches and the following is the current preferred one:

- Make a new command line option `field_lists` which will be similar to the field_counts command.
- Make a new field_list table for each summary table that requires field lists, called for example `awards_field_list`
- Make a new view for each summary table which joins the summary table to the new field_list table and adds a field_list column. This new view can be called for example `tmp_award_summary_with_field_list`
- Rename current summary tables/views to new name for example `award_summary_no_field_list`
- Rename `tmp_award_summary_with_field_list` to `award_summary`
- Copy over all comments from `award_summary_no_field_list` to new `award_summary` view and add a comment for the new `field_list` column.

The effect of doing the above will be that the summary tables will appear the same to end user as they currently do, just with the new field_list column added.  Also if the `doc_table_ref` is run after this command is run then the docs should be exported correctly.  We should make it clear that the `field_list` field only appears if the command is run in the docs.

In doing the above we will need a list of summary tables that need a field_list and what their primary keys are.  With this list we can generate the sql needed for the above. This list can be stored as a global in `manage.py`

The major downside of the above approach is the extra tables made. These other tables/views can not be dropped as they are depended upon by the new views.

**Comment by jpmckinney** [comment]
Sounds good. To check that I understand correctly: there will be a `--field-lists` option on the `add` command. If the user didn't specify it originally, they need to `remove` the schema, then `add` it again.

For steps 3-5, it seems simpler to:

(3) Do current step (4).
(4) Do current step (3) but name the table/view award_summary
(5) No step (5).

The current code abandons the target of having tables always available as it added unnecessary complexity. If a user needs tables to be available while re-creating the schema, they can just create a new schema with a different name, then remove the old one after the new one is ready.

**Comment by kindly** [comment]
Great and agreed that the change in the steps outlined above is simpler.

**Comment by kindly** [comment]
@duncandewhurst This has been completed and is on the server.

Shall we keep this ticket open for a bit so you can check if it behaves as expected.

**Comment by duncandewhurst** [comment]
Sounds good! I started a [testing notebook](https://colab.research.google.com/drive/18Repdx3tY1lvEAjvxsril_WWHSrUOkbj) which can also serve as an introduction to the new functionality for helpdesk analysts.

Everything looks good so far, but I noticed that the array notation used in the [documentation](https://kingfisher-summarize.readthedocs.io/en/latest/cli/use.html#create-array-of-all-paths-for-each-row-in-each-summary-table) doesn't work with the `%%sql` magic introduced in https://github.com/open-contracting/kingfisher-colab/issues/29, so for use in notebooks we'll need to use `ARRAY[]` instead.

**Comment by kindly** [comment]
There is another option we could consider that I only thought of after @jpmckinney expected the new field to be a JSONB not a TEXT[].

We could make the new field a JSONB but an object with NULL values. It would look like:
```
  {"/apath": None,
   "/anotherpath": None}
```
This on the surface looks ugly but has a few advantages:

- The fields would be unique.  Meaning the space taken up would likely be smaller.
- The creation time would be very similar because if we did a `jsonb_object_agg` (instead of an `array_agg`) it would mean we can do a group by without a group by subquery while also ignoring duplicates.
- The querying on the field is nicer as it gives us 3 different operators to use 

    - `? <text>` for simple contains
    - `?| <text[]>` one of the items in text array
    - `?& <text[]>` all items in text array.    

- I imagine the query time may be faster too as it is searching by key rather that iterating over the array.

Just wanted to get this out before it is used widely.

**Comment by jpmckinney** [comment]
Good idea! Happy for you to make the change.

**Comment by duncandewhurst** [comment]
I tested the new approach and it looks good to me.

I've updated the testing notebook and will share it with the other analysts once the new version of Kingfisher Colab is released on PyPI, since it uses the `%%sql` magic.

**Comment by duncandewhurst** [comment]
Shared in CRM-6830
