### ISSUE TITLE
Add payer and payee summaries

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-summarize#6]
Currently we have summary tables for all organization references in the schema, except payer and payee.

If we add those we can add checks on whether payee and payer organization references have associated entries in the parties array with the correct roles declared to our data feedback reports.

This is fairly low priority, since few publishers use those fields at present.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kingfisher-views: Add new aggregates/fields](https://trello.com/c/1Ta2HPcR/105-kingfisher-views-add-new-aggregates-fields)

**Comment by jpmckinney** [comment]
The described check is already performed by Pelican.

Since the fields are rarely disclosed, they are not especially relevant to analysis.

As such, I'll close this issue until there is new demand.
